services:
  _defaults:
    autowire: true
    autoconfigure: true

  SFErTrack\RollbarSymfonyBundle\Service\RollbarWrapper: ~

  SFErTrack\RollbarSymfonyBundle\Service\RollbarHandlerFactory:
    arguments:
      $config: '%rollbar.config%'
      $environment: '%kernel.environment%'

  monolog_rollbar_handler:
    class: Monolog\Handler\RollbarHandler
    factory: ['@SFErTrack\RollbarSymfonyBundle\Service\RollbarHandlerFactory', createRollbarHandler]
    tags:
      - { name: monolog.logger, channel: rollbar }

  SFErTrack\RollbarSymfonyBundle\Service\Scrubber\ScrubberFacade: ~
  SFErTrack\RollbarSymfonyBundle\Service\PersonProvider\PersonProviderFacade: ~
  SFErTrack\RollbarSymfonyBundle\Service\CheckIgnore\CheckIgnoreFacade: ~
  SFErTrack\RollbarSymfonyBundle\Service\Exception\ExceptionExtraDataFacade: ~
  SFErTrack\RollbarSymfonyBundle\Service\Exception\ExceptionExtraDataProvider: ~