services:
  _defaults:
    autowire: true
    autoconfigure: true

  Ant\RollbarSymfonyBundle\Service\RollbarWrapper: ~

  Ant\RollbarSymfonyBundle\Service\RollbarHandlerFactory:
    arguments:
      $config: '%rollbar.config%'
      $environment: '%kernel.environment%'

  monolog_rollbar_handler:
    factory: ['@Ant\RollbarSymfonyBundle\Service\RollbarHandlerFactory', createRollbarHandler]
    tags:
      - { name: monolog.logger, channel: rollbar }

  Ant\RollbarSymfonyBundle\Service\PersonProvider\PersonProviderFacade: ~
  Ant\RollbarSymfonyBundle\Service\CheckIgnore\CheckIgnoreFacade: ~
  Ant\RollbarSymfonyBundle\Service\Exception\ExceptionExtraDataFacade: ~
  Ant\RollbarSymfonyBundle\Service\Exception\ExceptionExtraDataProvider: ~