services:
  _defaults:
    autowire: true
    autoconfigure: true

  SFErTrack\RollbarSymfonyBundle\Service\RollbarReporter: ~

  SFErTrack\RollbarSymfonyBundle\Service\RollbarLoggerFactory:
    arguments:
      $config: '%rollbar.config%'
      $env: '%kernel.environment%'
      $projectDir: '%kernel.project_dir%'

  Rollbar\RollbarLogger:
    lazy: true
    public: true
    factory: '@SFErTrack\RollbarSymfonyBundle\Service\RollbarLoggerFactory'

  Monolog\Handler\RollbarHandler:
    lazy: true
    tags:
      - { name: monolog.logger, channel: rollbar }

  SFErTrack\RollbarSymfonyBundle\Service\Scrubber\ScrubberFacade: ~
  SFErTrack\RollbarSymfonyBundle\Service\Scrubber\CookieScrubber:
    arguments:
      $scrubFields: '%rollbar.config.scrubber_cookie_fields%'
  SFErTrack\RollbarSymfonyBundle\Service\Scrubber\DefaultScrubber:
    arguments:
      $scrubFields: '%rollbar.config.scrub_fields%'
      $safelist: '%rollbar.config.scrub_safelist%'
      $scrubEnvVariables: '%rollbar.config.scrub_env_variables%'
  SFErTrack\RollbarSymfonyBundle\Service\Scrubber\LocalVarsSecretsScrubber:
    arguments:
      $safelist: '%rollbar.config.scrub_safelist%'
      $scrubEnvVariables: '%rollbar.config.scrub_env_variables%'
  SFErTrack\RollbarSymfonyBundle\Service\PersonProvider\PersonProviderFacade: ~
  SFErTrack\RollbarSymfonyBundle\Service\CheckIgnore\CheckIgnoreFacade: ~
  SFErTrack\RollbarSymfonyBundle\Service\Exception\ExceptionExtraDataFacade: ~
  SFErTrack\RollbarSymfonyBundle\Service\Exception\ExceptionExtraDataProvider: ~
