name: Code quality check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests (PHP ${{ matrix.php }} / Symfony ${{ matrix.symfony }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.3', '8.4' ]
        symfony: [ '6.4.*', '7.2.*', '7.3.*']
        include:
          - php: '8.1'
            symfony: '6.4.*'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP, with Composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      # https://symfony.com/doc/current/bundles/best_practices.html#require-a-specific-symfony-version
      - name: Set specific symfony version
        run: SYMFONY_REQUIRE=${{ matrix.symfony }} printenv SYMFONY_REQUIRE

      - name: Install Symfony Flex
        run: composer global config --no-plugins allow-plugins.symfony/flex true && composer global require --no-progress --no-scripts --no-plugins symfony/flex

      - name: Install composer dependencies
        run: SYMFONY_REQUIRE=${{ matrix.symfony }} composer update --prefer-dist --no-progress

      - name: Run code quality tools
        run: PHP_CS_FIXER_IGNORE_ENV=1 composer run-script code-quality
