name: Code quality check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests (PHP ${{ matrix.php }} / Symfony ${{ matrix.symfony }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']
        symfony: ['6.4.*', '7.0.*', '7.1.*']

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP, with Composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        run: SYMFONY_REQUIRE=${{ matrix.symfony }} composer update --no-progress

      - name: Run code quality tools
        run: composer run-script code-quality
